//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyMoney.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easyMoney.Data.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit payment.
        /// </summary>
        internal static string BenefitPaymentDefault {
            get {
                return ResourceManager.GetString("BenefitPaymentDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit payment for insured event..
        /// </summary>
        internal static string BenefitPaymentMessage {
            get {
                return ResourceManager.GetString("BenefitPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit (insurance) payment.
        /// </summary>
        internal static string BenefitPaymentTitle {
            get {
                return ResourceManager.GetString("BenefitPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus is received.
        /// </summary>
        internal static string BonusDefault {
            get {
                return ResourceManager.GetString("BonusDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get a bonus (in addition to your salary)..
        /// </summary>
        internal static string BonusMessage {
            get {
                return ResourceManager.GetString("BonusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string BonusTitle {
            get {
                return ResourceManager.GetString("BonusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow money.
        /// </summary>
        internal static string BorrowedDefault {
            get {
                return ResourceManager.GetString("BorrowedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You borrow money from somebody. Account for borrowed money should exist..
        /// </summary>
        internal static string BorrowedMessage {
            get {
                return ResourceManager.GetString("BorrowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow money.
        /// </summary>
        internal static string BorrowedTitle {
            get {
                return ResourceManager.GetString("BorrowedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity.
        /// </summary>
        internal static string CharityDefault {
            get {
                return ResourceManager.GetString("CharityDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You spend money on charity..
        /// </summary>
        internal static string CharityMessage {
            get {
                return ResourceManager.GetString("CharityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity.
        /// </summary>
        internal static string CharityTitle {
            get {
                return ResourceManager.GetString("CharityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        internal static string CommunicationDefault {
            get {
                return ResourceManager.GetString("CommunicationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for communications (phone, mobile, internet and so on)..
        /// </summary>
        internal static string CommunicationMessage {
            get {
                return ResourceManager.GetString("CommunicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication costs.
        /// </summary>
        internal static string CommunicationTitle {
            get {
                return ResourceManager.GetString("CommunicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetic treatments.
        /// </summary>
        internal static string CosmeticTreatmentsDefault {
            get {
                return ResourceManager.GetString("CosmeticTreatmentsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetic beauty treatments (haircut, manicure, pedicure and so on)..
        /// </summary>
        internal static string CosmeticTreatmentsMessage {
            get {
                return ResourceManager.GetString("CosmeticTreatmentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetic treatments.
        /// </summary>
        internal static string CosmeticTreatmentsTitle {
            get {
                return ResourceManager.GetString("CosmeticTreatmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt repayment.
        /// </summary>
        internal static string CreditRepaymentDefault {
            get {
                return ResourceManager.GetString("CreditRepaymentDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select proper credit account and put amount which you spent on this payment and correct amount (could be less) for reduction on credit account..
        /// </summary>
        internal static string CreditRepaymentMessage {
            get {
                return ResourceManager.GetString("CreditRepaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit/card/debt repayment.
        /// </summary>
        internal static string CreditRepaymentTitle {
            get {
                return ResourceManager.GetString("CreditRepaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt is returned.
        /// </summary>
        internal static string DebtReturnedDefault {
            get {
                return ResourceManager.GetString("DebtReturnedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get back lended money. Account for lended money should exist..
        /// </summary>
        internal static string DebtReturnedMessage {
            get {
                return ResourceManager.GetString("DebtReturnedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt is returned.
        /// </summary>
        internal static string DebtReturnedTitle {
            get {
                return ResourceManager.GetString("DebtReturnedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string DinnerDefault {
            get {
                return ResourceManager.GetString("DinnerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner or breakfast..
        /// </summary>
        internal static string DinnerMessage {
            get {
                return ResourceManager.GetString("DinnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner/breakfast.
        /// </summary>
        internal static string DinnerTitle {
            get {
                return ResourceManager.GetString("DinnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividents are received.
        /// </summary>
        internal static string DividentsDefault {
            get {
                return ResourceManager.GetString("DividentsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive dividents, those could be paid to you via cash or any other debit account..
        /// </summary>
        internal static string DividentsMessage {
            get {
                return ResourceManager.GetString("DividentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividents.
        /// </summary>
        internal static string DividentsTitle {
            get {
                return ResourceManager.GetString("DividentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string EntertainmentDefault {
            get {
                return ResourceManager.GetString("EntertainmentDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses on movies, restaurants, cafes and other entertainment..
        /// </summary>
        internal static string EntertainmentMessage {
            get {
                return ResourceManager.GetString("EntertainmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string EntertainmentTitle {
            get {
                return ResourceManager.GetString("EntertainmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay fine.
        /// </summary>
        internal static string FineDefault {
            get {
                return ResourceManager.GetString("FineDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine/penalty payment..
        /// </summary>
        internal static string FineMessage {
            get {
                return ResourceManager.GetString("FineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine/penalty.
        /// </summary>
        internal static string FineTitle {
            get {
                return ResourceManager.GetString("FineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift is given.
        /// </summary>
        internal static string GiftGivenDefault {
            get {
                return ResourceManager.GetString("GiftGivenDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You give money to somebody as a gift..
        /// </summary>
        internal static string GiftGivenMessage {
            get {
                return ResourceManager.GetString("GiftGivenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a gift.
        /// </summary>
        internal static string GiftGivenTitle {
            get {
                return ResourceManager.GetString("GiftGivenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift is received.
        /// </summary>
        internal static string GiftReceivedDefault {
            get {
                return ResourceManager.GetString("GiftReceivedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get money as a gift..
        /// </summary>
        internal static string GiftReceivedMessage {
            get {
                return ResourceManager.GetString("GiftReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive a gift.
        /// </summary>
        internal static string GiftReceivedTitle {
            get {
                return ResourceManager.GetString("GiftReceivedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance fee.
        /// </summary>
        internal static string InsuranceFeeDefault {
            get {
                return ResourceManager.GetString("InsuranceFeeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment for insurance..
        /// </summary>
        internal static string InsuranceFeeMessage {
            get {
                return ResourceManager.GetString("InsuranceFeeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance fee.
        /// </summary>
        internal static string InsuranceFeeTitle {
            get {
                return ResourceManager.GetString("InsuranceFeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest on deposit.
        /// </summary>
        internal static string InterestDefault {
            get {
                return ResourceManager.GetString("InterestDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest is paid to you on your deposit account..
        /// </summary>
        internal static string InterestMessage {
            get {
                return ResourceManager.GetString("InterestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest on deposit.
        /// </summary>
        internal static string InterestTitle {
            get {
                return ResourceManager.GetString("InterestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item sold.
        /// </summary>
        internal static string ItemSoldDefault {
            get {
                return ResourceManager.GetString("ItemSoldDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sell something of your own and get money for it..
        /// </summary>
        internal static string ItemSoldMessage {
            get {
                return ResourceManager.GetString("ItemSoldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item sold.
        /// </summary>
        internal static string ItemSoldTitle {
            get {
                return ResourceManager.GetString("ItemSoldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend money.
        /// </summary>
        internal static string LendedDefault {
            get {
                return ResourceManager.GetString("LendedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lend money to somebody. Account for lended money should exist..
        /// </summary>
        internal static string LendedMessage {
            get {
                return ResourceManager.GetString("LendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend money.
        /// </summary>
        internal static string LendedTitle {
            get {
                return ResourceManager.GetString("LendedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical expenses.
        /// </summary>
        internal static string MedicalDefault {
            get {
                return ResourceManager.GetString("MedicalDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical expenses - pharmacy, hospital and so on..
        /// </summary>
        internal static string MedicalMessage {
            get {
                return ResourceManager.GetString("MedicalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical expenses.
        /// </summary>
        internal static string MedicalTitle {
            get {
                return ResourceManager.GetString("MedicalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string OtherIncomeDefault {
            get {
                return ResourceManager.GetString("OtherIncomeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any other type of income (specify details in description)..
        /// </summary>
        internal static string OtherIncomeMessage {
            get {
                return ResourceManager.GetString("OtherIncomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other income.
        /// </summary>
        internal static string OtherIncomeTitle {
            get {
                return ResourceManager.GetString("OtherIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string OtherPaymentDefault {
            get {
                return ResourceManager.GetString("OtherPaymentDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any other type of payment (specify details in description)..
        /// </summary>
        internal static string OtherPaymentMessage {
            get {
                return ResourceManager.GetString("OtherPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other payment.
        /// </summary>
        internal static string OtherPaymentTitle {
            get {
                return ResourceManager.GetString("OtherPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet expenses.
        /// </summary>
        internal static string PetExpensesDefault {
            get {
                return ResourceManager.GetString("PetExpensesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses on your pets (cat, dog and so on)..
        /// </summary>
        internal static string PetExpensesMessage {
            get {
                return ResourceManager.GetString("PetExpensesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet expenses.
        /// </summary>
        internal static string PetExpensesTitle {
            get {
                return ResourceManager.GetString("PetExpensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize is received.
        /// </summary>
        internal static string PrizeDefault {
            get {
                return ResourceManager.GetString("PrizeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won money as a prize..
        /// </summary>
        internal static string PrizeMessage {
            get {
                return ResourceManager.GetString("PrizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        internal static string PrizeTitle {
            get {
                return ResourceManager.GetString("PrizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big purchase.
        /// </summary>
        internal static string PurchaseDefault {
            get {
                return ResourceManager.GetString("PurchaseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant purchase. Regular shopping should be filled separately..
        /// </summary>
        internal static string PurchaseMessage {
            get {
                return ResourceManager.GetString("PurchaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big purchase.
        /// </summary>
        internal static string PurchaseTitle {
            get {
                return ResourceManager.GetString("PurchaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase return.
        /// </summary>
        internal static string ReturnDefault {
            get {
                return ResourceManager.GetString("ReturnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get your money back on return of purchased goods..
        /// </summary>
        internal static string ReturnMessage {
            get {
                return ResourceManager.GetString("ReturnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return of purchased goods.
        /// </summary>
        internal static string ReturnTitle {
            get {
                return ResourceManager.GetString("ReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string SalaryDefault {
            get {
                return ResourceManager.GetString("SalaryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary is paid to you, for extra pays there is also Bonus transaction..
        /// </summary>
        internal static string SalaryMessage {
            get {
                return ResourceManager.GetString("SalaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string SalaryTitle {
            get {
                return ResourceManager.GetString("SalaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for services.
        /// </summary>
        internal static string ServicesDefault {
            get {
                return ResourceManager.GetString("ServicesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for some services. Services should be clarified in description..
        /// </summary>
        internal static string ServicesMessage {
            get {
                return ResourceManager.GetString("ServicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for services.
        /// </summary>
        internal static string ServicesTitle {
            get {
                return ResourceManager.GetString("ServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string ShoppingDefault {
            get {
                return ResourceManager.GetString("ShoppingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular everyday shopping, significant purchases should be filled separately..
        /// </summary>
        internal static string ShoppingMessage {
            get {
                return ResourceManager.GetString("ShoppingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string ShoppingTitle {
            get {
                return ResourceManager.GetString("ShoppingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport expenses.
        /// </summary>
        internal static string SportDefault {
            get {
                return ResourceManager.GetString("SportDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses on sport, fitness, yoga and other activities..
        /// </summary>
        internal static string SportMessage {
            get {
                return ResourceManager.GetString("SportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport expenses.
        /// </summary>
        internal static string SportTitle {
            get {
                return ResourceManager.GetString("SportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay taxes.
        /// </summary>
        internal static string TaxDefault {
            get {
                return ResourceManager.GetString("TaxDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax/duty payment..
        /// </summary>
        internal static string TaxMessage {
            get {
                return ResourceManager.GetString("TaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax return.
        /// </summary>
        internal static string TaxReturnDefault {
            get {
                return ResourceManager.GetString("TaxReturnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get some of your taxes back..
        /// </summary>
        internal static string TaxReturnMessage {
            get {
                return ResourceManager.GetString("TaxReturnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax return.
        /// </summary>
        internal static string TaxReturnTitle {
            get {
                return ResourceManager.GetString("TaxReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        internal static string TaxTitle {
            get {
                return ResourceManager.GetString("TaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money transfer.
        /// </summary>
        internal static string TransferDefault {
            get {
                return ResourceManager.GetString("TransferDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money transfer between debit accounts (for example, cash taken from the debit card, or currency exchange)..
        /// </summary>
        internal static string TransferMessage {
            get {
                return ResourceManager.GetString("TransferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money transfer.
        /// </summary>
        internal static string TransferTitle {
            get {
                return ResourceManager.GetString("TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        internal static string TransportationDefault {
            get {
                return ResourceManager.GetString("TransportationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation (bus, taxi and so on) expenses..
        /// </summary>
        internal static string TransportationMessage {
            get {
                return ResourceManager.GetString("TransportationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation expenses.
        /// </summary>
        internal static string TransportationTitle {
            get {
                return ResourceManager.GetString("TransportationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for public utilities.
        /// </summary>
        internal static string UtilitiesDefault {
            get {
                return ResourceManager.GetString("UtilitiesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for public utilities..
        /// </summary>
        internal static string UtilitiesMessage {
            get {
                return ResourceManager.GetString("UtilitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for public utilities.
        /// </summary>
        internal static string UtilitiesTitle {
            get {
                return ResourceManager.GetString("UtilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle expenses.
        /// </summary>
        internal static string VehicleExpensesDefault {
            get {
                return ResourceManager.GetString("VehicleExpensesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses on car/bike or other moving vehicle (fuel, service and so on)..
        /// </summary>
        internal static string VehicleExpensesMessage {
            get {
                return ResourceManager.GetString("VehicleExpensesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle expenses.
        /// </summary>
        internal static string VehicleExpensesTitle {
            get {
                return ResourceManager.GetString("VehicleExpensesTitle", resourceCulture);
            }
        }
    }
}
