//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyMoney.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easyMoney.Manager.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account and amount.
        /// </summary>
        internal static string AccountAmountGroupBoxLabel {
            get {
                return ResourceManager.GetString("AccountAmountGroupBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct account balance.
        /// </summary>
        internal static string AccountBalanceButtonToolTip {
            get {
                return ResourceManager.GetString("AccountBalanceButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account balance correction.
        /// </summary>
        internal static string AccountCorrectionLabel {
            get {
                return ResourceManager.GetString("AccountCorrectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hidden.
        /// </summary>
        internal static string AccountHidden {
            get {
                return ResourceManager.GetString("AccountHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation found these problems with this account:
        ///
        ///{0}
        ///
        ///This prevents account from being saved. Please, correct errors and then try again..
        /// </summary>
        internal static string AccountValidationErrorsFoundFormat {
            get {
                return ResourceManager.GetString("AccountValidationErrorsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account validation information.
        /// </summary>
        internal static string AccountValidationTitle {
            get {
                return ResourceManager.GetString("AccountValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation found these problems with this account:
        ///
        ///{0}
        ///
        ///Would you like to save account anyway?.
        /// </summary>
        internal static string AccountValidationWarningsFoundFormat {
            get {
                return ResourceManager.GetString("AccountValidationWarningsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, respond....
        /// </summary>
        internal static string ActionNeededMessage {
            get {
                return ResourceManager.GetString("ActionNeededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney is starting up....
        /// </summary>
        internal static string ApplicationLoadingMessage {
            get {
                return ResourceManager.GetString("ApplicationLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance: {0:C}.
        /// </summary>
        internal static string BalanceFormat {
            get {
                return ResourceManager.GetString("BalanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will set account balance afterwards.
        /// </summary>
        internal static string BalanceLaterHint {
            get {
                return ResourceManager.GetString("BalanceLaterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete all custom metadata?
        ///
        ///WARNING! All accounts, plans, transactions based on custom metadata will be deleted permanently. This operation could not be undone!.
        /// </summary>
        internal static string ClearCustomMetadataMessage {
            get {
                return ResourceManager.GetString("ClearCustomMetadataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete all custom metadata?.
        /// </summary>
        internal static string ClearCustomMetadataTitle {
            get {
                return ResourceManager.GetString("ClearCustomMetadataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy: {0}.
        /// </summary>
        internal static string CopyFormat {
            get {
                return ResourceManager.GetString("CopyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should define accounts first!.
        /// </summary>
        internal static string CreateAccountsFirst {
            get {
                return ResourceManager.GetString("CreateAccountsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney is loading data file....
        /// </summary>
        internal static string DataLoadingMessage {
            get {
                return ResourceManager.GetString("DataLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney v{0}.
        /// </summary>
        internal static string DefaultFormTitleFormat {
            get {
                return ResourceManager.GetString("DefaultFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney is ready.
        /// </summary>
        internal static string DefaultStatus {
            get {
                return ResourceManager.GetString("DefaultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete account: {0}?
        ///
        ///All transactions with this account will remain in the list, but account balance will be removed from your assets or debts..
        /// </summary>
        internal static string DeleteAccountFormat {
            get {
                return ResourceManager.GetString("DeleteAccountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account?.
        /// </summary>
        internal static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete planned transaction: {0}?
        ///
        ///There is a paired planned transaction; by deleting this planned transaction you will also delete paired one..
        /// </summary>
        internal static string DeletePairedPlannedTransactionFormat {
            get {
                return ResourceManager.GetString("DeletePairedPlannedTransactionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete transaction: {0}?
        ///
        ///There is a paired transaction; by deleting this transaction you will also delete paired one..
        /// </summary>
        internal static string DeletePairedTransactionFormat {
            get {
                return ResourceManager.GetString("DeletePairedTransactionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete planned transaction: {0}?.
        /// </summary>
        internal static string DeletePlannedTransactionFormat {
            get {
                return ResourceManager.GetString("DeletePlannedTransactionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete planned transaction?.
        /// </summary>
        internal static string DeletePlannedTransactionTitle {
            get {
                return ResourceManager.GetString("DeletePlannedTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete tag &apos;{0}&apos;?
        ///
        ///This tag will be removed from all information entries. This operation could not be undone!.
        /// </summary>
        internal static string DeleteTagFormat {
            get {
                return ResourceManager.GetString("DeleteTagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected tag?.
        /// </summary>
        internal static string DeleteTagTitle {
            get {
                return ResourceManager.GetString("DeleteTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete transaction: {0}?.
        /// </summary>
        internal static string DeleteTransactionFormat {
            get {
                return ResourceManager.GetString("DeleteTransactionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete transaction?.
        /// </summary>
        internal static string DeleteTransactionTitle {
            get {
                return ResourceManager.GetString("DeleteTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag could not be empty string..
        /// </summary>
        internal static string EmptyTagNotAllowed {
            get {
                return ResourceManager.GetString("EmptyTagNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney data files (*.xemdf)|*.xemdf|All files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New income.
        /// </summary>
        internal static string NewIncomeLabel {
            get {
                return ResourceManager.GetString("NewIncomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New payment.
        /// </summary>
        internal static string NewPaymentLabel {
            get {
                return ResourceManager.GetString("NewPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no accounts defined!
        ///
        ///Switching you to Accounts tab, where you can define proper accounts..
        /// </summary>
        internal static string NoAccountsText {
            get {
                return ResourceManager.GetString("NoAccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no accounts defined!.
        /// </summary>
        internal static string NoAccountsTitle {
            get {
                return ResourceManager.GetString("NoAccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney v{0} is up to date.
        ///No newer releases are available at this time..
        /// </summary>
        internal static string NoUpdatesFormat {
            get {
                return ResourceManager.GetString("NoUpdatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney is up to date.
        /// </summary>
        internal static string NoUpdatesTitle {
            get {
                return ResourceManager.GetString("NoUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect. Please, enter correct password..
        /// </summary>
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password NOT active.
        /// </summary>
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password active.
        /// </summary>
        internal static string PasswordValid {
            get {
                return ResourceManager.GetString("PasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned transaction is implemented..
        /// </summary>
        internal static string PlanImplementedToolTip {
            get {
                return ResourceManager.GetString("PlanImplementedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned: {0}.
        /// </summary>
        internal static string PlannedTemplateFormat {
            get {
                return ResourceManager.GetString("PlannedTemplateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a transaction implementing this plan.
        /// </summary>
        internal static string PlannedTransactionSubmitButtonToolTip {
            get {
                return ResourceManager.GetString("PlannedTransactionSubmitButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation found these problems with this planned transaction:
        ///
        ///{0}
        ///
        ///This prevents planned transaction from being saved. Please, correct errors and then try again..
        /// </summary>
        internal static string PlannedTransactionValidationErrorsFoundFormat {
            get {
                return ResourceManager.GetString("PlannedTransactionValidationErrorsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned transaction validation information.
        /// </summary>
        internal static string PlannedTransactionValidationTitle {
            get {
                return ResourceManager.GetString("PlannedTransactionValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation found these problems with this planned transaction:
        ///
        ///{0}
        ///
        ///Would you like to save planned transaction anyway?.
        /// </summary>
        internal static string PlannedTransactionValidationWarningsFoundFormat {
            get {
                return ResourceManager.GetString("PlannedTransactionValidationWarningsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned transaction is NOT implemented!.
        /// </summary>
        internal static string PlanNotImplementedToolTip {
            get {
                return ResourceManager.GetString("PlanNotImplementedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned transaction is not implemented yet..
        /// </summary>
        internal static string PlanNotImplementedYetToolTip {
            get {
                return ResourceManager.GetString("PlanNotImplementedYetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait....
        /// </summary>
        internal static string PleaseWaitMessage {
            get {
                return ResourceManager.GetString("PleaseWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney v{0} - {1}.
        /// </summary>
        internal static string PortableFormTitleFormat {
            get {
                return ResourceManager.GetString("PortableFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, until {1:d}.
        /// </summary>
        internal static string RecurrencyUntilFormat {
            get {
                return ResourceManager.GetString("RecurrencyUntilFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day, {0}.
        /// </summary>
        internal static string StatsDay {
            get {
                return ResourceManager.GetString("StatsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month, {0}.
        /// </summary>
        internal static string StatsMonth {
            get {
                return ResourceManager.GetString("StatsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year, {0}.
        /// </summary>
        internal static string StatsYear {
            get {
                return ResourceManager.GetString("StatsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag &apos;{0}&apos; already exist, please use different string..
        /// </summary>
        internal static string TagAlreadyExistFormat {
            get {
                return ResourceManager.GetString("TagAlreadyExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming tag.
        /// </summary>
        internal static string TagRenameErrorTitle {
            get {
                return ResourceManager.GetString("TagRenameErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all resources with tag &apos;{0}&apos;.
        /// </summary>
        internal static string TagToolTipFormat {
            get {
                return ResourceManager.GetString("TagToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction template requires account of type [{0}].
        ///
        ///Please, create proper account to use this transaction template..
        /// </summary>
        internal static string TemplateAccountNotFoundFormat {
            get {
                return ResourceManager.GetString("TemplateAccountNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required account not found.
        /// </summary>
        internal static string TemplateAccountNotFoundTitle {
            get {
                return ResourceManager.GetString("TemplateAccountNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        internal static string TransactionDestinationValidation {
            get {
                return ResourceManager.GetString("TransactionDestinationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction is not planned..
        /// </summary>
        internal static string TransactionNotPlanned {
            get {
                return ResourceManager.GetString("TransactionNotPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string TransactionSourceValidation {
            get {
                return ResourceManager.GetString("TransactionSourceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation found these problems with this transaction:
        ///
        ///{0}
        ///
        ///This prevents transaction from being saved. Please, correct errors and then try again..
        /// </summary>
        internal static string TransactionValidationErrorsFoundFormat {
            get {
                return ResourceManager.GetString("TransactionValidationErrorsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction validation information.
        /// </summary>
        internal static string TransactionValidationTitle {
            get {
                return ResourceManager.GetString("TransactionValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation found these problems with this transaction:
        ///
        ///{0}
        ///
        ///Would you like to save transaction anyway?.
        /// </summary>
        internal static string TransactionValidationWarningsFoundFormat {
            get {
                return ResourceManager.GetString("TransactionValidationWarningsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of easyMoney available for download.
        ///You are running version {0}, and {1} is available.
        ///
        ///Update will be downloaded in background. easyMoney will be restarted and upgraded when update is ready.
        ///
        ///Do you want to proceed with update?.
        /// </summary>
        internal static string UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("UpdateAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New easyMoney is available.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney is checking for updates....
        /// </summary>
        internal static string UpdateCheckStatus {
            get {
                return ResourceManager.GetString("UpdateCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney is downloading update....
        /// </summary>
        internal static string UpdateDownloadingStatus {
            get {
                return ResourceManager.GetString("UpdateDownloadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during update process:
        ///
        ///{0}
        ///
        ///Please, contact easyMoney developers regarding this error..
        /// </summary>
        internal static string UpdateErrorFormat {
            get {
                return ResourceManager.GetString("UpdateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update checking error.
        /// </summary>
        internal static string UpdateErrorTitle {
            get {
                return ResourceManager.GetString("UpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney update failed!.
        /// </summary>
        internal static string UpdateFailedStatus {
            get {
                return ResourceManager.GetString("UpdateFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easyMoney is up to date.
        /// </summary>
        internal static string UpdatesNotFoundStatus {
            get {
                return ResourceManager.GetString("UpdatesNotFoundStatus", resourceCulture);
            }
        }
    }
}
