//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyMoney.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easyMoney.Data.Resources.TransactionTypes", typeof(TransactionTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit payment (insurance).
        /// </summary>
        internal static string BenefitPaymentTitle {
            get {
                return ResourceManager.GetString("BenefitPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string BonusTitle {
            get {
                return ResourceManager.GetString("BonusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed money amount increase.
        /// </summary>
        internal static string BorrowedIncreaseTitle {
            get {
                return ResourceManager.GetString("BorrowedIncreaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow money.
        /// </summary>
        internal static string BorrowTitle {
            get {
                return ResourceManager.GetString("BorrowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity.
        /// </summary>
        internal static string CharityTitle {
            get {
                return ResourceManager.GetString("CharityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        internal static string CommunicationTitle {
            get {
                return ResourceManager.GetString("CommunicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account balance correction.
        /// </summary>
        internal static string CorrectionTitle {
            get {
                return ResourceManager.GetString("CorrectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetic treatments.
        /// </summary>
        internal static string CosmeticTreatmentsTitle {
            get {
                return ResourceManager.GetString("CosmeticTreatmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit amount reduction.
        /// </summary>
        internal static string CreditReductionTitle {
            get {
                return ResourceManager.GetString("CreditReductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit repayment.
        /// </summary>
        internal static string CreditRepaymentTitle {
            get {
                return ResourceManager.GetString("CreditRepaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt amount increase.
        /// </summary>
        internal static string DebtIncreaseTitle {
            get {
                return ResourceManager.GetString("DebtIncreaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt amount reduction.
        /// </summary>
        internal static string DebtReductionTitle {
            get {
                return ResourceManager.GetString("DebtReductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt returned.
        /// </summary>
        internal static string DebtReturnedTitle {
            get {
                return ResourceManager.GetString("DebtReturnedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner/breakfast.
        /// </summary>
        internal static string DinnerTitle {
            get {
                return ResourceManager.GetString("DinnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividents.
        /// </summary>
        internal static string DividentsTitle {
            get {
                return ResourceManager.GetString("DividentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string EntertainmentTitle {
            get {
                return ResourceManager.GetString("EntertainmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        internal static string FineTitle {
            get {
                return ResourceManager.GetString("FineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift (given).
        /// </summary>
        internal static string GiftGivenTitle {
            get {
                return ResourceManager.GetString("GiftGivenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift (received).
        /// </summary>
        internal static string GiftReceivedTitle {
            get {
                return ResourceManager.GetString("GiftReceivedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance fee.
        /// </summary>
        internal static string InsuranceFeeTitle {
            get {
                return ResourceManager.GetString("InsuranceFeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit interest.
        /// </summary>
        internal static string InterestTitle {
            get {
                return ResourceManager.GetString("InterestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item sold.
        /// </summary>
        internal static string ItemSoldTitle {
            get {
                return ResourceManager.GetString("ItemSoldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend money.
        /// </summary>
        internal static string LendTitle {
            get {
                return ResourceManager.GetString("LendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical expenses.
        /// </summary>
        internal static string MedicalTitle {
            get {
                return ResourceManager.GetString("MedicalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other income.
        /// </summary>
        internal static string OtherIncomeTitle {
            get {
                return ResourceManager.GetString("OtherIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other payment.
        /// </summary>
        internal static string OtherPaymentTitle {
            get {
                return ResourceManager.GetString("OtherPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string PaymentTitle {
            get {
                return ResourceManager.GetString("PaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet expenses.
        /// </summary>
        internal static string PetExpensesTitle {
            get {
                return ResourceManager.GetString("PetExpensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        internal static string PrizeTitle {
            get {
                return ResourceManager.GetString("PrizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big purchase.
        /// </summary>
        internal static string PurchaseTitle {
            get {
                return ResourceManager.GetString("PurchaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase return.
        /// </summary>
        internal static string ReturnTitle {
            get {
                return ResourceManager.GetString("ReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string SalaryTitle {
            get {
                return ResourceManager.GetString("SalaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment for services.
        /// </summary>
        internal static string ServicesTitle {
            get {
                return ResourceManager.GetString("ServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular shopping.
        /// </summary>
        internal static string ShoppingTitle {
            get {
                return ResourceManager.GetString("ShoppingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport expenses.
        /// </summary>
        internal static string SportTitle {
            get {
                return ResourceManager.GetString("SportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax return.
        /// </summary>
        internal static string TaxReturnTitle {
            get {
                return ResourceManager.GetString("TaxReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string TaxTitle {
            get {
                return ResourceManager.GetString("TaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer (in).
        /// </summary>
        internal static string TransferInTitle {
            get {
                return ResourceManager.GetString("TransferInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer (out).
        /// </summary>
        internal static string TransferOutTitle {
            get {
                return ResourceManager.GetString("TransferOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation expenses.
        /// </summary>
        internal static string TransportationTitle {
            get {
                return ResourceManager.GetString("TransportationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public utilities.
        /// </summary>
        internal static string UtilitiesTitle {
            get {
                return ResourceManager.GetString("UtilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle expenses.
        /// </summary>
        internal static string VehicleExpensesTitle {
            get {
                return ResourceManager.GetString("VehicleExpensesTitle", resourceCulture);
            }
        }
    }
}
