//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyMoney.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easyMoney.Data.Resources.ValidationRules", typeof(ValidationRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans and borrowed accounts should have negative balance. Please, ensure that such account will have negative balance after the transaction..
        /// </summary>
        internal static string CreditAccountsNegativeBalanceMessage {
            get {
                return ResourceManager.GetString("CreditAccountsNegativeBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans and borrowed money accounts should have negative balance.
        /// </summary>
        internal static string CreditAccountsNegativeBalanceTitle {
            get {
                return ResourceManager.GetString("CreditAccountsNegativeBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card accounts should have negative balance..
        /// </summary>
        internal static string CreditCardNegativeBalanceMessage {
            get {
                return ResourceManager.GetString("CreditCardNegativeBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card accounts should have negative balance.
        /// </summary>
        internal static string CreditCardNegativeBalanceTitle {
            get {
                return ResourceManager.GetString("CreditCardNegativeBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit accounts should have positive balance..
        /// </summary>
        internal static string DebitPositiveBalanceMessage {
            get {
                return ResourceManager.GetString("DebitPositiveBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit accounts should have positive balance.
        /// </summary>
        internal static string DebitPositiveBalanceTitle {
            get {
                return ResourceManager.GetString("DebitPositiveBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only account balance correction transaction could have negative amount. Use only positive amounts in transactions..
        /// </summary>
        internal static string OnlyCorrectionNegativeMessage {
            get {
                return ResourceManager.GetString("OnlyCorrectionNegativeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only account balance correction transaction could have negative amount.
        /// </summary>
        internal static string OnlyCorrectionNegativeTitle {
            get {
                return ResourceManager.GetString("OnlyCorrectionNegativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount should not be zero..
        /// </summary>
        internal static string TransactionNonZeroMessage {
            get {
                return ResourceManager.GetString("TransactionNonZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount should not be zero.
        /// </summary>
        internal static string TransactionNonZeroTitle {
            get {
                return ResourceManager.GetString("TransactionNonZeroTitle", resourceCulture);
            }
        }
    }
}
