//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyMoney.SimpleReports.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easyMoney.SimpleReports.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows changes in assets and debts for period specified..
        /// </summary>
        internal static string ActualBalanceChangesDescription {
            get {
                return ResourceManager.GetString("ActualBalanceChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance changes, from {0} to {1}.
        /// </summary>
        internal static string ActualBalanceChangesFormTitleFormat {
            get {
                return ResourceManager.GetString("ActualBalanceChangesFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance changes.
        /// </summary>
        internal static string ActualBalanceChangesTitle {
            get {
                return ResourceManager.GetString("ActualBalanceChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows amounts recevied and spent for the period for each tag in a graphical form. Please, note that transactions without tags will not be included in this report..
        /// </summary>
        internal static string AmountByTagsChartDescription {
            get {
                return ResourceManager.GetString("AmountByTagsChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount by tags (chart).
        /// </summary>
        internal static string AmountByTagsChartTitle {
            get {
                return ResourceManager.GetString("AmountByTagsChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows amounts recevied and spent for the period for each tag. Please, note that transactions without tags will not be included in this report..
        /// </summary>
        internal static string AmountByTagsDescription {
            get {
                return ResourceManager.GetString("AmountByTagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount by tags, from {0} to {1}.
        /// </summary>
        internal static string AmountByTagsFormTitleFormat {
            get {
                return ResourceManager.GetString("AmountByTagsFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount by tags.
        /// </summary>
        internal static string AmountByTagsTitle {
            get {
                return ResourceManager.GetString("AmountByTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows total amounts for each transaction type in graphical form for the period selected. All transactions (including balance correction) will be included in this report..
        /// </summary>
        internal static string AmountsByTransactionTypesDescription {
            get {
                return ResourceManager.GetString("AmountsByTransactionTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amounts by transaction types, from {0} to {1}.
        /// </summary>
        internal static string AmountsByTransactionTypesFormTitleFormat {
            get {
                return ResourceManager.GetString("AmountsByTransactionTypesFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amounts by transaction types.
        /// </summary>
        internal static string AmountsByTransactionTypesTitle {
            get {
                return ResourceManager.GetString("AmountsByTransactionTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountTitle {
            get {
                return ResourceManager.GetString("AmountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets (planned).
        /// </summary>
        internal static string AssetsPlannedTitle {
            get {
                return ResourceManager.GetString("AssetsPlannedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string AssetsTitle {
            get {
                return ResourceManager.GetString("AssetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time.
        /// </summary>
        internal static string DateTimeTitle {
            get {
                return ResourceManager.GetString("DateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateTitle {
            get {
                return ResourceManager.GetString("DateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day totals:.
        /// </summary>
        internal static string DayTotalsTitle {
            get {
                return ResourceManager.GetString("DayTotalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts (planned).
        /// </summary>
        internal static string DebtsPlannedTitle {
            get {
                return ResourceManager.GetString("DebtsPlannedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        internal static string DebtsTitle {
            get {
                return ResourceManager.GetString("DebtsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        internal static string DeltaTitle {
            get {
                return ResourceManager.GetString("DeltaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation, another day.
        /// </summary>
        internal static string DeviationAnotherDayTitle {
            get {
                return ResourceManager.GetString("DeviationAnotherDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation from plan.
        /// </summary>
        internal static string DeviationFromPlanTitle {
            get {
                return ResourceManager.GetString("DeviationFromPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string DifferenceIconTitle {
            get {
                return ResourceManager.GetString("DifferenceIconTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        internal static string DifferenceTitle {
            get {
                return ResourceManager.GetString("DifferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned.
        /// </summary>
        internal static string EarnedTitle {
            get {
                return ResourceManager.GetString("EarnedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned to earn.
        /// </summary>
        internal static string EarnTitle {
            get {
                return ResourceManager.GetString("EarnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On different day.
        /// </summary>
        internal static string ImplementedOnAnotherDayTitle {
            get {
                return ResourceManager.GetString("ImplementedOnAnotherDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ImplementedTitle {
            get {
                return ResourceManager.GetString("ImplementedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        internal static string ImplementsTitle {
            get {
                return ResourceManager.GetString("ImplementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month balance report shows transactions and plans for the month in tabular view. This report uses color coding of the rows as follows:
        /// * green lines - transactions that were planned;
        /// * blue lines - transactions which were planned and should be implemented in future;
        /// * red lines - transactions which were planned but not implemented;
        /// * orange lines - transactions which weren&apos;t planned.
        ///This report also sums differences for the each day and whole month. Less difference is better (this means, that mont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonthBalanceDescription {
            get {
                return ResourceManager.GetString("MonthBalanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month balance for {0:Y}.
        /// </summary>
        internal static string MonthBalanceFormTitleFormat {
            get {
                return ResourceManager.GetString("MonthBalanceFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month balance.
        /// </summary>
        internal static string MonthBalanceTitle {
            get {
                return ResourceManager.GetString("MonthBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month totals:.
        /// </summary>
        internal static string MonthTotalsTitle {
            get {
                return ResourceManager.GetString("MonthTotalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not done!.
        /// </summary>
        internal static string NotImplementedTitle {
            get {
                return ResourceManager.GetString("NotImplementedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not done yet.
        /// </summary>
        internal static string NotImplementedYetTitle {
            get {
                return ResourceManager.GetString("NotImplementedYetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not planned!.
        /// </summary>
        internal static string NotPlannedTitle {
            get {
                return ResourceManager.GetString("NotPlannedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account types shown: {0}.
        /// </summary>
        internal static string OnlyAccountTypes {
            get {
                return ResourceManager.GetString("OnlyAccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags shown: {0}.
        /// </summary>
        internal static string OnlyTags {
            get {
                return ResourceManager.GetString("OnlyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction types shown: {0}.
        /// </summary>
        internal static string OnlyTransactionTypesTypes {
            get {
                return ResourceManager.GetString("OnlyTransactionTypesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        internal static string PlannedAmountTitle {
            get {
                return ResourceManager.GetString("PlannedAmountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows changes in assets and debts according to current plans..
        /// </summary>
        internal static string PlannedBalanceChangesDescription {
            get {
                return ResourceManager.GetString("PlannedBalanceChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance forecast, from {0} to {1}.
        /// </summary>
        internal static string PlannedBalanceChangesFormTitleFormat {
            get {
                return ResourceManager.GetString("PlannedBalanceChangesFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance forecast.
        /// </summary>
        internal static string PlannedBalanceChangesTitle {
            get {
                return ResourceManager.GetString("PlannedBalanceChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string PlanTitle {
            get {
                return ResourceManager.GetString("PlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant difference!.
        /// </summary>
        internal static string SignificantDifferenceTitle {
            get {
                return ResourceManager.GetString("SignificantDifferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending structure report shows a pie chart describing structure of your spending by transaction types..
        /// </summary>
        internal static string SpendingStructureDescription {
            get {
                return ResourceManager.GetString("SpendingStructureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending structure, from {0} to {1}.
        /// </summary>
        internal static string SpendingStructureFormTitleFormat {
            get {
                return ResourceManager.GetString("SpendingStructureFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending structure.
        /// </summary>
        internal static string SpendingStructureTitle {
            get {
                return ResourceManager.GetString("SpendingStructureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned to spend.
        /// </summary>
        internal static string SpendTitle {
            get {
                return ResourceManager.GetString("SpendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent.
        /// </summary>
        internal static string SpentTitle {
            get {
                return ResourceManager.GetString("SpentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string TagsTitle {
            get {
                return ResourceManager.GetString("TagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string TagTitle {
            get {
                return ResourceManager.GetString("TagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TransactionAmountTitle {
            get {
                return ResourceManager.GetString("TransactionAmountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows transactions done on selected accounts in tabular form. .
        /// </summary>
        internal static string TransactionsByAccountDescription {
            get {
                return ResourceManager.GetString("TransactionsByAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions by account: {0}, from {1} to {2}.
        /// </summary>
        internal static string TransactionsByAccountFormTitleFormat {
            get {
                return ResourceManager.GetString("TransactionsByAccountFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions by account.
        /// </summary>
        internal static string TransactionsByAccountTitle {
            get {
                return ResourceManager.GetString("TransactionsByAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string TransactionsTitle {
            get {
                return ResourceManager.GetString("TransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string TransactionTitle {
            get {
                return ResourceManager.GetString("TransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string TypeIconTitle {
            get {
                return ResourceManager.GetString("TypeIconTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeTitle {
            get {
                return ResourceManager.GetString("TypeTitle", resourceCulture);
            }
        }
    }
}
