//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyMoney.Setup.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easyMoney.Setup.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this account type?
        ///
        ///All data related to this account type will be deleted permanently! This action could not be undone!.
        /// </summary>
        internal static string DeleteAccountTypeText {
            get {
                return ResourceManager.GetString("DeleteAccountTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this currency?
        ///
        ///All data related to this currency will be deleted permanently! This action could not be undone!.
        /// </summary>
        internal static string DeleteCurrencyText {
            get {
                return ResourceManager.GetString("DeleteCurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete metadata item?.
        /// </summary>
        internal static string DeleteItemTitle {
            get {
                return ResourceManager.GetString("DeleteItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this template?
        ///
        ///All transactions and plans built on this template will be deleted permanently! This action could not be undone!.
        /// </summary>
        internal static string DeleteTemplateText {
            get {
                return ResourceManager.GetString("DeleteTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this transaction type?
        ///
        ///All data related to this transaction type will be deleted permanently! This action could not be undone!.
        /// </summary>
        internal static string DeleteTransactionTypeText {
            get {
                return ResourceManager.GetString("DeleteTransactionTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save information.
        /// </summary>
        internal static string ErrorSavingTitle {
            get {
                return ResourceManager.GetString("ErrorSavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Add new item...&gt;.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, there is no default currency set. easyMoney needs a currency with exchange rate 1 to be set. This currency will be considered as default.
        ///
        ///Please, set exchange rate of 1 to the currency which you&apos;re typically use (and update exchange rates for other currencies)..
        /// </summary>
        internal static string NoDefaultCurrencyText {
            get {
                return ResourceManager.GetString("NoDefaultCurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default currency!.
        /// </summary>
        internal static string NoDefaultCurrencyTitle {
            get {
                return ResourceManager.GetString("NoDefaultCurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate could not be zero!
        ///
        ///Please, set non-zero exchange rate..
        /// </summary>
        internal static string NonZeroExchangeRateText {
            get {
                return ResourceManager.GetString("NonZeroExchangeRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with ID &quot;{0}&quot; already exist.
        ///
        ///Please, use different value in ID field..
        /// </summary>
        internal static string RecordExistFormat {
            get {
                return ResourceManager.GetString("RecordExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User metadata entry ID should have prefix &quot;{0}&quot;!
        ///
        ///Please, add this prefix to ID field..
        /// </summary>
        internal static string UserIDShouldHavePrefixFormat {
            get {
                return ResourceManager.GetString("UserIDShouldHavePrefixFormat", resourceCulture);
            }
        }
    }
}
