//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyMoney.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Introduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Introduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easyMoney.Manager.Resources.Introduction", typeof(Introduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fprq2\fcharset204 Verdana;}{\f2\fnil\fcharset2 Symbol;}}
        ///\viewkind4\uc1\pard\lang1033\f0\fs20 To keep track of your money, you need to define your accounts. Without defining accounts, you can&apos;t submit any transaction.\par
        ///\par
        ///Accounts in \i easyMoney \i0 could include:\par
        ///\pard{\pntext\f2\&apos;B7\tab}{\*\pn\pnlvlblt\pnf2\pnindent0{\pntxtb\&apos;B7}}\fi-284\li284\b cash\b0 ;\par
        ///\b{\pntext\f2\&apos;B7\tab}debit cards\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountsText {
            get {
                return ResourceManager.GetString("AccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts concept.
        /// </summary>
        internal static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fnil\fcharset2 Symbol;}}
        ///\viewkind4\uc1\pard\lang1033\f0\fs20 Now you know the basics of \i easyMoney\i0 .\par
        ///\par
        ///Here are some actions that you could do right now:\par
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-284\li284 define \b your accounts\b0 , starting with \b cash \b0 (count current balance for each account); do not forget about \b debts \b0 and \b loans\b0 , if you have th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NextStepsText {
            get {
                return ResourceManager.GetString("NextStepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next steps.
        /// </summary>
        internal static string NextStepsTitle {
            get {
                return ResourceManager.GetString("NextStepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fnil\fcharset2 Symbol;}}
        ///\viewkind4\uc1\pard\lang1033\f0\fs20 If you want to have a better control over your finances, you should plan your income and spending.\par
        ///\par
        ///Plans are very similar to transactions, expect:\par
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-284\li284 plans do not have exact account (only account type);\par
        ///{\pntext\f1\&apos;B7\tab}plans could be recurrent (for exa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlansText {
            get {
                return ResourceManager.GetString("PlansText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning your transactions.
        /// </summary>
        internal static string PlansTitle {
            get {
                return ResourceManager.GetString("PlansTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fnil\fcharset2 Symbol;}}
        ///\viewkind4\uc1\pard\lang1033\f0\fs20 Reporting is the most important feature of \i easyMoney\i0 . Reports are showing the information you entered in different forms. \par
        ///Currently, \i easyMoney \i0 has these reports:\par
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-284\li284\b Amounts by tags \b0 - shows total amounts spent and earned for each tag in tabular fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportsText {
            get {
                return ResourceManager.GetString("ReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports - check your income and spending.
        /// </summary>
        internal static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}}
        ///\viewkind4\uc1\pard\lang1033\f0\fs20 When you have a lot of plans and transactions, it is easier to find something using tags. In \i easyMoney \i0 each information piece (account, plan, transaction) could have set of tags. You are free to use any tags, which you decide suitable. \par
        ///\par
        ///For example, typical tags would be: &quot;car&quot;, &quot;internet&quot;, &quot;phone&quot;, &quot;movies&quot;, &quot;vacation&quot; or any other.\par
        ///\par
        ///Tags could help you  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TagsText {
            get {
                return ResourceManager.GetString("TagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags - categorize everything.
        /// </summary>
        internal static string TagsTitle {
            get {
                return ResourceManager.GetString("TagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\lang1033\f0\fs20 By transaction \i easyMoney \i0 understands any financial operation. All transactions could be divided into groups:\par
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-284\li284\b income \b0 - transactions when you receive money;\par
        ///\b{\pntext\f1\&apos;B7\tab}payment \b0 - transactions when you s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransactionsText {
            get {
                return ResourceManager.GetString("TransactionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions - all your financial activities.
        /// </summary>
        internal static string TransactionsTitle {
            get {
                return ResourceManager.GetString("TransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fprq2\fcharset204 Verdana;}{\f2\fnil\fcharset2 Symbol;}}
        ///\viewkind4\uc1\pard\lang1033\f0\fs20 Welcome to \i easyMoney \i0 - personal finance management software.\par
        ///\par
        ///\i easyMoney \i0 will help you to:\par
        ///\pard{\pntext\f2\&apos;B7\tab}{\*\pn\pnlvlblt\pnf2\pnindent0{\pntxtb\&apos;B7}}\fi-284\li284 monitor your assets and debts;\par
        ///{\pntext\f2\&apos;B7\tab}keep track of your income and spending;\par
        ///{\pntext\f2\&apos;B7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to easyMoney.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
